# Generated by Django 5.0.6 on 2024-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_unavailableday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('denied', 'Denied'), ('flagged', 'Flagged'), ('to_completion', 'To Completion')], default='pending', max_length=20),
        ),
    ]
