# Generated by Django 5.0.6 on 2024-08-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailableday',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
