# Generated by Django 5.0.6 on 2024-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_availableday_delete_unavailableday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableday',
            name='reason',
        ),
        migrations.AddField(
            model_name='availableday',
            name='type',
            field=models.CharField(choices=[('tea_tasting', 'Tea Tasting'), ('intro_gongfu', 'Intro to Gongfu'), ('guided_meditation', 'Guided Meditation')], default='tea_tasting', max_length=20),
        ),
    ]
