# Generated by Django 5.0.6 on 2024-08-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_remove_availableday_reason_availableday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day_type',
            field=models.CharField(choices=[('tea_tasting', 'Tea Tasting'), ('intro_gongfu', 'Intro to Gongfu'), ('guided_meditation', 'Guided Meditation')], default='tea_tasting', max_length=20),
        ),
    ]
