# Generated by Django 5.0.6 on 2024-10-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='walk_in_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='walk_in_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='walk_in_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='walk_in_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
